=== ftrackhq/integrations/projects/framework-common-extensions/schemas/schema/tool-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "http://www.ftrack.com/integrations/framework/simple-tool-schema.json",
  "title": "ToolSchema",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "tool_title",
    "host_type",
    "tool_type",
    "engine_type",
    "engine_name",
    "validation_schema"
  ],
  "properties": {
    "validation_schema": {
      "type": "string"
    },
    "tool_type": {
      "type": "string"
    },
    "tool_title": {
      "type": "string",
      "default": null
    },
    "host_type": {
      "type": "string",
      "default": "python"
    },
    "ui_type": {
      "type": "string",
      "default": ""
    },
    "discoverable": {
      "type": "array",
      "items": {"type": "string"},
      "default": [
        "Task"
      ]
    },
    "steps": {
            "type": "array",
            "items": {"$ref": "memory:StepSchema"},
            "minItems": 1,
            "uniqueItems": true
        },
    "plugins": {
            "type": "array",
            "items": {"$ref": "memory:PluginSchema"},
            "minItems": 1,
            "uniqueItems": true
        },
    "engine_type": {
          "type": "string"
        },
    "engine_name": {
          "type": "string"
        }
  }
}

=== ftrackhq/integrations/framework_hooks/framework-core-tool-configs/source/ftrack_framework_core_tool_configs/publisher/standalone-file-publish.json
{
  "tool_type": "publisher",
  "tool_title": "File Publisher",
  "host_type": "python",
  "ui_type": "qt",
  "engine_name": "load_publish",
  "engine_type": "publisher",
  "validation_schema": "ToolSchema",
  "steps":[
    {
      "step_type": "context",
      "step_name": "main",
      "optional": false,
      "enabled": true,
      "stages": [
        {
          "stage_type": "context",
          "stage_name": "context",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
                "plugin_type": "context",
                "plugin_title": "context selector",
                "plugin_name": "generic_context_passthrough",
                "widget_name": "publisher_context_selector"
            }
          ]
        }
      ]
    },
    {
      "step_type": "component",
      "step_name": "file",
      "optional": false,
      "enabled": true,
      "stages": [
        {
          "stage_type": "collector",
          "stage_name": "collector",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
              "plugin_type": "collector",
              "plugin_title": "collect file",
              "plugin_name": "file_collector",
              "widget_name": "file_browser_collector",
              "options": {
                "folder_path": null,
                "file_name": null
              }
            }
          ]
        },
        {
          "stage_type": "validator",
          "stage_name": "validator",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
              "plugin_type": "validator",
              "plugin_title": "validate file exists",
              "plugin_name": "file_exists_validator",
              "widget_name": "validator_check"
            }
          ]
        },
        {
          "stage_type": "exporter",
          "stage_name": "exporter",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
              "plugin_type": "exporter",
              "plugin_title": "Export file",
              "plugin_name": "rename_file_exporter",
              "widget_name": "file_exporter_options",
              "options": {
                "export_destinations": "/Users/ftrack/Desktop/myPublishedFiile.png"
              }
            }
          ]
        }
      ]
    },
    {
      "step_type": "component",
      "step_name": "file_two",
      "optional": false,
      "enabled": true,
      "stages": [
        {
          "stage_type": "collector",
          "stage_name": "collector",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
              "plugin_type": "collector",
              "plugin_title": "collect file",
              "plugin_name": "file_collector",
              "widget_name": "file_browser_collector",
              "options": {
                "folder_path": "/Users/ftrack/Desktop",
                "file_name": "file_collector_test.png"
              }
            }
          ]
        },
        {
          "stage_type": "validator",
          "stage_name": "validator",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
              "plugin_type": "validator",
              "plugin_title": "validate file exists",
              "plugin_name": "file_exists_validator",
              "widget_name": "validator_check"
            }
          ]
        },
        {
          "stage_type": "exporter",
          "stage_name": "exporter",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
              "plugin_type": "exporter",
              "plugin_title": "Export file",
              "plugin_name": "rename_file_exporter",
              "widget_name": "file_exporter_options",
              "options": {
                "export_destinations": "/Users/ftrack/Desktop/myPublishedFiile.png"
              }
            }
          ]
        }
      ]
    },
    {
      "step_type": "finalizer",
      "step_name": "main",
      "optional": false,
      "enabled": true,
      "stages": [
        {
          "stage_type": "pre_finalizer",
          "stage_name": "pre_finalizer",
          "optional": false,
          "enabled": true,
          "visible": false,
          "plugins": [
            {
              "plugin_type": "pre_finalizer",
              "plugin_title": "Pre publish to ftrack server",
              "plugin_name": "generic_passthrough"
            }
          ]
        },
        {
          "stage_type": "finalizer",
          "stage_name": "finalizer",
          "optional": false,
          "enabled": true,
          "visible": false,
          "plugins": [
            {
              "plugin_type": "finalizer",
              "plugin_title": "Publish to ftrack server",
              "plugin_name": "publish_to_ftrack"
            }
          ]
        },
        {
          "stage_type": "post_finalizer",
          "stage_name": "post_finalizer",
          "optional": false,
          "enabled": true,
          "visible": false,
          "plugins": [
            {
              "plugin_type": "post_finalizer",
              "plugin_title": "Post process publish",
              "plugin_name": "generic_passthrough"
            }
          ]
        }
      ]
    }
  ]
}

=== ftrackhq/integrations/projects/framework-photoshop/extensions/tool-configs/opener/photoshop-document-opener.json
{
  "tool_type": "opener",
  "tool_title": "Document Opener",
  "host_type": "python",
  "ui_type": "qt",
  "engine_name": "load_publish",
  "engine_type": "opener",
  "validation_schema": "ToolSchema",
  "steps":[
    {
      "step_type": "context",
      "step_name": "main",
      "optional": false,
      "enabled": true,
      "stages": [
        {
          "stage_type": "context",
          "stage_name": "context",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
                "plugin_type": "context",
                "plugin_title": "context selector",
                "plugin_name": "generic_context_passthrough"
            }
          ]
        }
      ]
    },
    {
      "step_type": "component",
      "step_name": "snapshot",
      "optional": false,
      "enabled": true,
      "stages": [
        {
          "stage_type": "collector",
          "stage_name": "collector",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
              "plugin_type": "collector",
              "plugin_title": "collect file",
              "plugin_name": "path_collector",
              "widget_name": "item_browser_selector"
            }
          ]
        },
        {
          "stage_type": "importer",
          "stage_name": "importer",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
              "plugin_type": "importer",
              "plugin_title": "open PS document",
              "plugin_name": "photoshop_document_opener"
            }
          ]
        },
        {
          "stage_type": "post_importer",
          "stage_name": "post_importer",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
              "plugin_type": "post_importer",
              "plugin_title": "Set up document",
              "plugin_name": "setup_photoshop_document"
            }
          ]
        }
      ]
    },
    {
      "step_type": "finalizer",
      "step_name": "main",
      "optional": false,
      "enabled": true,
      "stages": [
        {
          "stage_type": "pre_finalizer",
          "stage_name": "pre_finalizer",
          "optional": false,
          "enabled": true,
          "visible": false,
          "plugins": [
            {
              "plugin_type": "pre_finalizer",
              "plugin_title": "Pre finalizer process",
              "plugin_name": "generic_passthrough"
            }
          ]
        },
        {
          "stage_type": "finalizer",
          "stage_name": "finalizer",
          "optional": false,
          "enabled": true,
          "visible": false,
          "plugins": [
            {
              "plugin_type": "finalizer",
              "plugin_title": "Finalizer process",
              "plugin_name": "photoshop_opener_finalizer"
            }
          ]
        },
        {
          "stage_type": "post_finalizer",
          "stage_name": "post_finalizer",
          "optional": false,
          "enabled": true,
          "visible": false,
          "plugins": [
            {
              "plugin_type": "post_finalizer",
              "plugin_title": "Post process publish",
              "plugin_name": "generic_passthrough"
            }
          ]
        }
      ]
    }
  ]
}

=== ftrackhq/integrations/framework_hooks/framework-photoshop-tool-configs/source/ftrack_framework_photoshop_tool_configs/publisher/image-photoshop-publish.json
{
  "tool_type": "publisher",
  "tool_title": "Document publisher",
  "host_type": "photoshop",
  "ui_type": "qt",
  "engine_name": "load_publish",
  "engine_type": "publisher",
  "validation_schema": "ToolSchema",
  "steps":[
    {
      "step_type": "context",
      "step_name": "main",
      "optional": false,
      "enabled": true,
      "stages": [
        {
          "stage_type": "context",
          "stage_name": "context",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
                "plugin_type": "context",
                "plugin_title": "context selector",
                "plugin_name": "generic_context_passthrough",
                "widget_name": "publisher_context_selector"
            }
          ]
        }
      ]
    },
    {
      "step_type": "component",
      "step_name": "snapshot",
      "optional": false,
      "enabled": true,
      "stages": [
        {
          "stage_type": "collector",
          "stage_name": "collector",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
              "plugin_type": "collector",
              "plugin_title": "collect file",
              "plugin_name": "photoshop_document_publisher_collector",
              "options": {
                "export": ["document"]
              }
            }
          ]
        },
        {
          "stage_type": "validator",
          "stage_name": "validator",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
              "plugin_type": "validator",
              "plugin_title": "validate document",
              "plugin_name": "photoshop_document_publisher_validator",
              "widget_name": "validator_check"
            }
          ]
        },
        {
          "stage_type": "exporter",
          "stage_name": "exporter",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
              "plugin_type": "exporter",
              "plugin_title": "Export file",
              "plugin_name": "photoshop_native_publisher_exporter"
            }
          ]
        }
      ]
    },
    {
      "step_type": "component",
      "step_name": "reviewable",
      "optional": true,
      "enabled": true,
      "stages": [
        {
          "stage_type": "collector",
          "stage_name": "collector",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
              "plugin_type": "collector",
              "plugin_title": "collect file",
              "plugin_name": "photoshop_document_publisher_collector",
              "options": {
                "export": ["document"]
              }
            }
          ]
        },
        {
          "stage_type": "validator",
          "stage_name": "validator",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
              "plugin_type": "validator",
              "plugin_title": "validate document",
              "plugin_name": "photoshop_document_publisher_validator",
              "widget_name": "validator_check"
            }
          ]
        },
        {
          "stage_type": "exporter",
          "stage_name": "exporter",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
              "plugin_type": "exporter",
              "plugin_title": "Export file",
              "plugin_name": "photoshop_image_publisher_exporter"
            }
          ]
        }
      ]
    },
    {
      "step_type": "finalizer",
      "step_name": "main",
      "optional": false,
      "enabled": true,
      "stages": [
        {
          "stage_type": "pre_finalizer",
          "stage_name": "pre_finalizer",
          "optional": false,
          "enabled": true,
          "visible": false,
          "plugins": [
            {
              "plugin_type": "pre_finalizer",
              "plugin_title": "Pre publish to ftrack server",
              "plugin_name": "generic_passthrough"
            }
          ]
        },
        {
          "stage_type": "finalizer",
          "stage_name": "finalizer",
          "optional": false,
          "enabled": true,
          "visible": false,
          "plugins": [
            {
              "plugin_type": "finalizer",
              "plugin_title": "Publish to ftrack server",
              "plugin_name": "publish_to_ftrack"
            }
          ]
        },
        {
          "stage_type": "post_finalizer",
          "stage_name": "post_finalizer",
          "optional": false,
          "enabled": true,
          "visible": false,
          "plugins": [
            {
              "plugin_type": "post_finalizer",
              "plugin_title": "Post process publish",
              "plugin_name": "generic_passthrough"
            }
          ]
        }
      ]
    }
  ]
}

=== ftrackhq/integrations/tests/framework/manual/hooks/framework-test-tool-configs/source/ftrack_framework_test_tool_configs/publisher/simple_tool_config.json
{
  "tool_type": "publisher",
  "tool_title": "Simple Tool",
  "host_type": "python",
  "ui_type": "qt",
  "engine_name": "load_publish",
  "engine_type": "publisher",
  "validation_schema": "ToolSchema",
  "plugins":[
      {
          "plugin_title": "collect file",
          "plugin_name": "file_collector",
          "widget_name": "file_browser_collector",
          "options": {
            "folder_path": null,
            "file_name": null
          }
      }
  ]
}

=== ftrackhq/integrations/framework_hooks/disney/framework-photoshop-tool-configs/source/ftrack_framework_photoshop_tool_configs/opener/photoshop-file-opener.json
{
  "tool_type": "opener",
  "tool_title": "File Opener",
  "host_type": "python",
  "ui_type": "qt",
  "engine_name": "load_publish",
  "engine_type": "opener",
  "validation_schema": "ToolSchema",
  "steps":[
    {
      "step_type": "context",
      "step_name": "main",
      "optional": false,
      "enabled": true,
      "stages": [
        {
          "stage_type": "context",
          "stage_name": "context",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
                "plugin_type": "context",
                "plugin_title": "context selector",
                "plugin_name": "generic_context_passthrough"
            }
          ]
        }
      ]
    },
    {
      "step_type": "component",
      "step_name": "snapshot",
      "optional": false,
      "enabled": true,
      "stages": [
        {
          "stage_type": "collector",
          "stage_name": "collector",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
              "plugin_type": "collector",
              "plugin_title": "collect file",
              "plugin_name": "component_path_collector",
              "widget_name": "asset_version_browser_collector"
            }
          ]
        },
        {
          "stage_type": "importer",
          "stage_name": "importer",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
              "plugin_type": "importer",
              "plugin_title": "open PS file",
              "plugin_name": "photoshop_file_opener"
            }
          ]
        },
        {
          "stage_type": "post_importer",
          "stage_name": "post_importer",
          "optional": false,
          "enabled": true,
          "plugins": [
            {
              "plugin_type": "post_importer",
              "plugin_title": "Set up scene",
              "plugin_name": "setup_photoshop_scene"
            }
          ]
        }
      ]
    },
    {
      "step_type": "finalizer",
      "step_name": "main",
      "optional": false,
      "enabled": true,
      "stages": [
        {
          "stage_type": "pre_finalizer",
          "stage_name": "pre_finalizer",
          "optional": false,
          "enabled": true,
          "visible": false,
          "plugins": [
            {
              "plugin_type": "pre_finalizer",
              "plugin_title": "Pre finalizer process",
              "plugin_name": "generic_passthrough"
            }
          ]
        },
        {
          "stage_type": "finalizer",
          "stage_name": "finalizer",
          "optional": false,
          "enabled": true,
          "visible": false,
          "plugins": [
            {
              "plugin_type": "finalizer",
              "plugin_title": "Finalizer process",
              "plugin_name": "generic_passthrough"
            }
          ]
        },
        {
          "stage_type": "post_finalizer",
          "stage_name": "post_finalizer",
          "optional": false,
          "enabled": true,
          "visible": false,
          "plugins": [
            {
              "plugin_type": "post_finalizer",
              "plugin_title": "Post process publish",
              "plugin_name": "generic_passthrough"
            }
          ]
        }
      ]
    }
  ]
}
